import { imageConfigDefault } from "next/dist/shared/lib/image-config";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Clients.module.scss";
// import { clients, serve, grew, social, develop, Ui } from "../../data/clients";
import { serve } from '../../data/clients'
import Script from "next/script";
import CountUp from "react-countup";
import AOS from "aos";
import "aos/dist/aos.css";
import Link from "next/link";

// import Size from "../utils/ScreenSize";

export default function Clients() {
  // Aos.init();
  return (
    <div className={styles.HomeContainer}>
      <Head>
        <title>Digiligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.svg" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />

        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
        {/* 
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
        <script>AOS.init();</script> */}
      </Head>
      <nav className={styles.nav}>
        <Image
          src="/images/logo.svg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />

        <div>
          <h6>
            <Link href="/">Home</Link>
          </h6>
          <h6>
            <Link href="/aboutus">About Us</Link>
          </h6>

          <span></span>
        </div>
      </nav>
      <main>
        {/* <section className={styles.serve}>
          <h2>INDUSTRIES WE SERVE</h2>
          <ul>
            {serve.map((list, index) => (
              <li key={index}>
                <Image
                  src={list} // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.grew}>
          <h2>START-UPS WE GREW WITH</h2>
          <ul>
            {grew.map((list, index) => (
              <li key={index}>
                <Image
                  src={list} // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
            ))}
          </ul>
        </section> */}

        {/* <section className={styles.market}>
          <h2>MOBILE APP & WEBSITE DEVELOPMENT</h2>
          <ul>
            {develop.map((list, index) => (
              <li key={index}>
                {list.map((img, imgIndex) => (
                  <div key={imgIndex}>
                    <Image
                      src={img} // Route of the image file
                      height={144} // Desired size with correct aspect ratio
                      width={144} // Desired size with correct aspect ratio
                      alt="Your Name"
                    />
                  </div>
                ))}
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.social}>
          <h2>UX/UI DESIGNING</h2>
          <ul>
            {social.map((list, index) => (
              <li key={index}>
                <div>
                  <Image
                    src={list} // Route of the image file
                    height={144} // Desired size with correct aspect ratio
                    width={144} // Desired size with correct aspect ratio
                    alt="Your Name"
                  />
                </div>
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.market}>
          <h2>UX/UI DESIGNING</h2>
          <ul>
            {Ui.map((list, index) => (
              <li key={index}>
                <div>
                  <Image
                    src={list} // Route of the image file
                    height={144} // Desired size with correct aspect ratio
                    width={144} // Desired size with correct aspect ratio
                    alt="Your Name"
                  />
                </div>
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.belowbanner}>
          <h4 data-aos="zoom-out">All Big things start</h4>
          <b>Let's connect over a cup of coffe</b>
          <button type="" data-aos="zoom-in">
            Book your Free Coffee
          </button>
        </section> */}
      </main>

      <footer className={styles.footer}>
        <div>
          <Image
            src="/images/logo.svg" // Route of the image file
            height={144} // Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
          />
          <p>
            Thane's Best Digital Marketing agency that believes in taking your
            ideas to the pinnacle of success.
          </p>
        </div>

        <ul>
          <li>Services</li>
          <li>Social Media Marketing</li>
          <li>Mobile Development</li>
          <li>Branding and Designing</li>
          <li>Website Development</li>
          <li>UI/UX Designing</li>
          <li>Search Engine Optimization </li>
        </ul>
        <ul>
          <li>Quick Links</li>
          <li>Our Work</li>
          <li>About Us</li>
          <li>Services</li>
          <li>
            Careers <span>We're hiring</span>
          </li>
        </ul>
        <ul>
          <li>Reach us</li>
          <li>
            <Image
              src="/images/footericons/email.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            biz@digillence.in
          </li>
          <li>
            <Image
              src="/images/footericons/location.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
          <li>
            <Image
              src="/images/footericons/phone.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
        </ul>
      </footer>

      <div className={styles.bottom}>2022 , Digiligence copyright</div>
    </div>
  );
}
