import { imageConfigDefault } from "next/dist/shared/lib/image-config";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Clients.module.scss";
import { serve, grew, social, develop, Ui } from "../../data/clients";

import Link from "next/link";

// import Size from "../utils/ScreenSize";

export default function Clients() {
  return (
    <div className={styles.HomeContainer}>
      <Head>
        <title>Digiligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.svg" />
      </Head>

      <main>
        <section className={styles.serve}>
          <h2>INDUSTRIES WE SERVE</h2>
          <ul>
            {serve.map((list, index) => (
              <li key={index}>
                <div>
                  <Image
                    src={list.img} // Route of the image file
                    height={1000} // Desired size with correct aspect ratio
                    width={1000} // Desired size with correct aspect ratio
                    alt="Your Name"
                    priority
                  />
                </div>

                <p>{list.caption}</p>
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.grew}>
          <h2>START-UPS WE GREW WITH</h2>
          <ul>
            {grew.map((list, index) => (
              <li key={index}>
                <Image
                  src={list} // Route of the image file
                  height={1000} // Desired size with correct aspect ratio
                  width={1000} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.market}>
          <h2>MOBILE APP & WEBSITE DEVELOPMENT</h2>
          <ul>
            {develop.map((list, index) => (
              <li key={index}>
                {list.map((img, imgIndex) => (
                  <div key={imgIndex}>
                    <Image
                      src={img} // Route of the image file
                      height={1000} // Desired size with correct aspect ratio
                      width={1000} // Desired size with correct aspect ratio
                      alt="Your Name"
                    />
                  </div>
                ))}
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.grid}>
          <h2>UX/UI DESIGNING</h2>
          <ul>
            <li></li>
            {social.map((list, index) => (
              <li key={index}>
                <Image
                  src={list} // Route of the image file
                  height={1000} // Desired size with correct aspect ratio
                  width={1000} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.belowbanner}>
          <h4 data-aos="zoom-out">All Big things start</h4>
          <b>Let's connect over a cup of coffe</b>
          <button type="" data-aos="zoom-in">
            Book your Free Coffee
          </button>
        </section>
      </main>
    </div>
  );
}
