import { imageConfigDefault } from "next/dist/shared/lib/image-config";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.scss";
import { clients, comments, service } from "../data/image";
// import Size from "../utils/ScreenSize";

export default function Home() {
  return (
    <div className={styles.HomeContainer}>
      <Head>
        <title>Digiligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.svg" />
      </Head>
      <nav className={styles.nav}>
        <Image
          src="/images/logo.svg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />

        <div>
          <h6>Clients</h6>
          <h6>Contact</h6>
          <span></span>
        </div>
      </nav>
      <main>
        <section className={styles.Banner}>
          <div>
            <div>
              <h2>
                Sky-Rocketing
                <span> your Business to </span>
                Digital heights
              </h2>
              <p>
                Building Robust Marketing strategies for your Businesses &
                Brands to deliver Best ROI with accelerated and sustainable
                growth.
              </p>
              <button>Know More</button>
              <button>Start Your Project</button>
            </div>
            <Image
              src="/images/Banner/1.png" // Route of the image file
              height={144} //Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
          </div>
        </section>
        <section className={styles.we}>
          <hr />
          <h2>We are Digiligence</h2>

          <p>
            Ranked as One of Thane’s Best Digital Marketing Agency. We don’t
            just grow Businesses, we build Brands. Blending art and technology
            to turn an idea into action. We cover the whole spectrum of Digital
            Marketing, from SEO optimization to Social Media Marketing and much
            more!{" "}
          </p>
        </section>

        <section className={styles.service}>
          <h3>Our Services</h3>
          <hr />

          <ul>
            {service.map((list, index) => (
              <li key={index}>
                <div>
                  <Image
                    src={list.img} // Route of the image file
                    height={144} //Desired size with correct aspect ratio
                    width={144} // Desired size with correct aspect ratio
                    alt="Your Name"
                  />
                </div>
                <p>{list.name}</p>
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.progress}>
          <ul>
            <li>
              <h3>200 +</h3>
              <h6>Projects Completed</h6>
            </li>
            <hr />
            <li>
              <h3>100+</h3>
              <h6>Clients across the globe</h6>
            </li>
            <hr />
            <li>
              <h3>200+</h3>
              <h6>Digital Consultations</h6>
            </li>
            <hr />
            <li>
              <h3>50+</h3>
              <h6>Start-Ups kick started</h6>
            </li>
          </ul>
        </section>

        <section className={styles.clients}>
          <h2>Our Clients</h2>
          <hr />
          <ul>
            {clients.map((list, index) => (
              <li key={index}>
                {list.map((img, imgIndex) => (
                  <div key={imgIndex}>
                    <Image
                      src={img} // Route of the image file
                      height={144} // Desired size with correct aspect ratio
                      width={144} // Desired size with correct aspect ratio
                      alt="Your Name"
                    />
                  </div>
                ))}
              </li>
            ))}
          </ul>
        </section>

        <section className={styles.testimonial}>
          <h2>Here's what our client says</h2>
          <hr />
          <div className={styles.carousel}>
            {comments.map((list, index) => (
              <div key={index}>
                <div className={styles.comment}>
                  <b>{list.comment}</b>
                  <p>{list.paragragh}</p>
                </div>
                <div className={styles.author}>
                  <Image
                    src={list.img}
                    height={144}
                    width={144}
                    alt="Your Name"
                  />
                  <div>
                    <b>{list.name}</b>
                    <p>{list.designation}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </section>

        <section className={styles.project}>
          <hr />
          <h3>Project We Boast about</h3>
          <div>
            <ul>
              <li>
                <Image
                  src="/images/Home/Project1/1.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project1/4.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
              <li>
                {" "}
                <Image
                  src="/images/Home/Project1/8.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
                <Image
                  src="/images/Home/Project1/5.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project1/2.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
              <li>
                <Image
                  src="/images/Home/Project1/3.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project1/7.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
            </ul>
            <div>
              <h6>Social Media</h6>
              <h2>Sea Garden, Goa</h2>
              <h5>From “Empty” to “Over Booked” -Sea Garden’s Success Story</h5>
              <button>View Success Story</button>
            </div>
          </div>
          <div>
            <div>
              <h6>Mobile App Development</h6>
              <h2>The Hours</h2>
              <h5>
                Wide range of Hotels & more in just one click -The Hours Mobile
                App
              </h5>
              <button>View Portfolio</button>
            </div>
            <ul>
              <li>
                <Image
                  src="/images/Home/Project2/1.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project2/5.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
              <li>
                {" "}
                <Image
                  src="/images/Home/Project2/2.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
                <Image
                  src="/images/Home/Project2/6.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
              <li>
                <Image
                  src="/images/Home/Project2/3.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project2/7.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
              <li>
                <Image
                  src="/images/Home/Project2/4.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
                <Image
                  src="/images/Home/Project2/8.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />{" "}
              </li>
            </ul>
          </div>
        </section>

        <section className={styles.projectM}>
          <hr />
          <h3>Project We Boast about</h3>
          <div>
            <div>
              <h6>Social Media</h6>
              <h2>Sea Garden, Goa</h2>
              <h5>From “Empty” to “Over Booked” -Sea Garden’s Success Story</h5>
              <button>View Success Story</button>
            </div>{" "}
            <Image
              src="/images/Home/Project1/2.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
            <Image
              src="/images/Home/Project1/3.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
            <span>
              <Image
                src="/images/Home/Project1/5.png" // Route of the image file
                height={144} // Desired size with correct aspect ratio
                width={144} // Desired size with correct aspect ratio
                alt="Your Name"
              />
              <Image
                src="/images/Home/Project1/8.png" // Route of the image file
                height={144} // Desired size with correct aspect ratio
                width={144} // Desired size with correct aspect ratio
                alt="Your Name"
              />
            </span>
            <Image
              src="/images/Home/Project1/7.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
          </div>

          <div className={styles.Time}>
            <Image
              src="/images/Home/Project2/4.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            <Image
              src="/images/Home/Project2/3.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
            <div>
              <h6>Mobile App Development</h6>
              <h2>The Hours</h2>
              <h5>
                Wide range of Hotels & more in just one click -The Hours Mobile
                App
              </h5>
              <button>View Portfolio</button>
            </div>
            <Image
              src="/images/Home/Project2/7.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
            <span>
              <Image
                src="/images/Home/Project2/1.png" // Route of the image file
                height={144} // Desired size with correct aspect ratio
                width={144} // Desired size with correct aspect ratio
                alt="Your Name"
              />{" "}
              <Image
                src="/images/Home/Project2/2.png" // Route of the image file
                height={144} // Desired size with correct aspect ratio
                width={144} // Desired size with correct aspect ratio
                alt="Your Name"
              />
            </span>
            <Image
              src="/images/Home/Project2/5.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />{" "}
          </div>
        </section>

        <section className={styles.contact}>
          <div>
            <hr />
            <h3>Contact us</h3>
            <ul>
              <li>
                <Image
                  src="/images/Home/contact/icon/phone.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt=" "
                />
                <p>+91 8655997455</p>
              </li>
              <li>
                <Image
                  src="/images/Home/contact/icon/map.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt=" "
                />
                <p>
                  Suite-409, Oracle Business Hub, Ambica Nagar Bustop, Wagle
                  Estate, Thane.
                </p>
              </li>
              <li>
                <Image
                  src="/images/Home/contact/icon/mail.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt=" "
                />
                <p>biz@digilligence.com</p>
              </li>
            </ul>
          </div>
          <div>
            <hr />
            <h3>Connect with us</h3>
            <ul>
              <li>
                <Image
                  src="/images/Home/contact/socialmedia/linkedin.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
              <li>
                <Image
                  src="/images/Home/contact/socialmedia/instagram.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
              <li>
                <Image
                  src="/images/Home/contact/socialmedia/facebook.png" // Route of the image file
                  height={144} // Desired size with correct aspect ratio
                  width={144} // Desired size with correct aspect ratio
                  alt="Your Name"
                />
              </li>
            </ul>
          </div>
        </section>

        <section className={styles.belowbanner}>
          <h4>All Big things start</h4>
          <b>Let's connect over a cup of coffe</b>
          <button type="">Book your Free Coffee</button>
        </section>
      </main>
      <footer className={styles.footer}>
        <div>
          <Image
            src="/images/logo.svg" // Route of the image file
            height={144} // Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
          />
          <p>
            Thane's Best Digital Marketing agency that believes in taking your
            ideas to the pinnacle of success.
          </p>
        </div>

        <ul>
          <li>Services</li>
          <li>Social Media Marketing</li>
          <li>Mobile Development</li>
          <li>Branding and Designing</li>
          <li>Website Development</li>
          <li>UI/UX Designing</li>
          <li>Search Engine Optimization </li>
        </ul>
        <ul>
          <li>Quick Links</li>
          <li>Our Work</li>
          <li>About Us</li>
          <li>Services</li>
          <li>
            Careers <span>We're hiring</span>
          </li>
        </ul>
        <ul>
          <li>Reach us</li>
          <li>
            <Image
              src="/images/footericons/email.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            biz@digillence.in
          </li>
          <li>
            <Image
              src="/images/footericons/location.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
          <li>
            <Image
              src="/images/footericons/phone.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
        </ul>
      </footer>
      <div className={styles.bottom}>2022 , Digiligence copyright</div>
    </div>
  );
}
