import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/AboutUs.module.scss";

// import Size from "../utils/ScreenSize";

export default function AboutUs() {
  return (
    <div className={styles.HomeContainer}>
      <Head>
        <title>Digiligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.svg" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
      </Head>

      <nav className={styles.nav}>
        <Image
          src="/./images/logo.svg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />

        <div>
          <h6>Clients</h6>
          <h6>Contact</h6>
          <span></span>
        </div>
      </nav>
      <main>
        <section className={styles.Banner}>
          <div>
            <div>
              <hr />
              <h4>About Us</h4>
              <h2 className="animate__animated animate__fadeInUp">
                <span> We Are Digiligence </span>
              </h2>
              <p className="animate__animated animate__fadeInUp">
                Any organization’s strength lies in the employees and rightly
                so, Team Digilligence is a power packed squad of Quaint Content
                Writers, Artistic Graphic Designers, experienced Content
                Strategists, technically sound UX/UI Designers, Skilled Website
                & Application Developers.
              </p>

              <button className="animate__animated animate__fadeInUp animate__delay-1s">
                Start Your Project
              </button>
            </div>
            <Image
              src="/./images/Banner/1.png" // Route of the image file
              height={144} //Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
              className="animate__animated animate__jackInTheBox"
            />
          </div>
        </section>
        <section className={styles.we}>
          <div>
            <hr />
            <h2>Our Process</h2>
            <hr />
          </div>

          <div>
            <img src="" alt="" />
            <h5>Strategize</h5>
            <p>
              After analyzing your requirements, our team will strategize & come
              with the Plan of Action. We begin quick by hunting the results
              needed to deliver immediate value, exceed expectations & out grow
              your competition!
            </p>
          </div>
        </section>
        <section className={styles.we}>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
          <div>
            <h2>What we do</h2>
            <hr />
            <p>
              We're a team of Young Guns lead by our Founder Mr. Mervin Agera
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
            <p>
              Building an Enterprise is still a matter of paperwork, but there's
              alot that goes in order to turn it into a Brand. We will build
              that Brand for you at Digilligence.
            </p>
          </div>
        </section>
        <section className={styles.we}>
          <div>
            <h2>Our Mission</h2>
            <hr />
            <p>
              We are on a Mission to provide Digital Business Solutions for all
              types of industries across the globe and help them stand on their
              feet.
            </p>
            <p>
              Our team is set on a Mission to Build Brands of tomorrow by
              understanding our client's goals & working towards achieving it.
              The Mission mainly includes helping Small Business and Startups
              reach new heights with the help of our Digital Services!
            </p>
          </div>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
        </section>
        <section className={styles.we}>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
          <div>
            <h2>Our Vision</h2>
            <hr />
            <p>
              We have Vision to help India reach the pinnacle of Digital success
              and contribute towards the growth of the nation. We believe in
              Mutual Growth; the organization plans on growing Internationally.
            </p>
            <p>
              With a futuristic vision, Team Digilligence looks to Cater to a
              wider audience with Empirical approach towa
            </p>
          </div>
        </section>
        <section className={styles.belowbanner}>
          <b>Let's connect over a cup of coffe</b>
          <button type="" data-aos="zoom-in">
            Book your Free Coffee
          </button>
        </section>
      </main>
      <footer className={styles.footer}>
        <div>
          <Image
            src="/./images/logo.svg" // Route of the image file
            height={144} // Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
          />
          <p>
            Thane's Best Digital Marketing agency that believes in taking your
            ideas to the pinnacle of success.
          </p>
        </div>

        <ul>
          <li>Services</li>
          <li>Social Media Marketing</li>
          <li>Mobile Development</li>
          <li>Branding and Designing</li>
          <li>Website Development</li>
          <li>UI/UX Designing</li>
          <li>Search Engine Optimization </li>
        </ul>
        <ul>
          <li>Quick Links</li>
          <li>Our Work</li>
          <li>About Us</li>
          <li>Services</li>
          <li>
            Careers <span>We're hiring</span>
          </li>
        </ul>
        <ul>
          <li>Reach us</li>
          <li>
            <Image
              src="/./images/footericons/email.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            biz@digillence.in
          </li>
          <li>
            <Image
              src="/./images/footericons/location.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
          <li>
            <Image
              src="/./images/footericons/phone.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
        </ul>
      </footer>
      <div className={styles.bottom}>2022 , Digiligence copyright</div>
    </div>
  );
}
