import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/AboutUs.module.scss";

// import Size from "../utils/ScreenSize";

export default function Home() {
  return (
    <div className={styles.HomeContainer}>
      <Head>
        <title>Digiligence</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logoicon.svg" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
        />
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        />
        <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>

        <script>AOS.init();</script>
      </Head>

      <nav className={styles.nav}>
        <Image
          src="/./images/logo.svg" // Route of the image file
          height={144} // Desired size with correct aspect ratio
          width={144} // Desired size with correct aspect ratio
          alt="Your Name"
        />

        <div>
          <h6>Clients</h6>
          <h6>Contact</h6>
          <span></span>
        </div>
      </nav>
      <main>
        <section className={styles.Banner}>
          <div>
            <div>
              <hr />
              <h4>About Us</h4>
              <h2 className="animate__animated animate__fadeInUp">
                <span> We Are Digiligence </span>
              </h2>
              <p className="animate__animated animate__fadeInUp">
                Any organization’s strength lies in the employees and rightly
                so, Team Digilligence is a power packed squad of Quaint Content
                Writers, Artistic Graphic Designers, experienced Content
                Strategists, technically sound UX/UI Designers, Skilled Website
                & Application Developers.
              </p>

              <button className="animate__animated animate__fadeInUp animate__delay-1s">
                Start Your Project
              </button>
            </div>
            <Image
              src="/./images/Banner/1.png" // Route of the image file
              height={144} //Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
              className="animate__animated animate__jackInTheBox"
            />
          </div>
        </section>
        <section className={styles.we}>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
          <div>
            <hr />
            <h2>We are Digiligence</h2>
            <p>
              We're a team of Young Guns lead by our Founder Mr. Mervin Agera
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
            <p>
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
          </div>
        </section>{" "}
        <section className={styles.we}>
          <div>
            <hr />
            <h2>We are Digiligence</h2>
            <p>
              We're a team of Young Guns lead by our Founder Mr. Mervin Agera
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
            <p>
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
          </div>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
        </section>{" "}
        <section className={styles.we}>
          <Image
            src="/./images/Banner/1.png" // Route of the image file
            height={144} //Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
            className="animate__animated animate__jackInTheBox"
          />
          <div>
            <hr />
            <h2>We are Digiligence</h2>
            <p>
              We're a team of Young Guns lead by our Founder Mr. Mervin Agera
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
            <p>
              who believes in the tech revolution and understands the importance
              of delivery timely results to all the client.
            </p>
          </div>
        </section>
        <section className={styles.belowbanner}>
          <b>Let's connect over a cup of coffe</b>
          <button type="" data-aos="zoom-in">
            Book your Free Coffee
          </button>
        </section>
      </main>
      <footer className={styles.footer}>
        <div>
          <Image
            src="/./images/logo.svg" // Route of the image file
            height={144} // Desired size with correct aspect ratio
            width={144} // Desired size with correct aspect ratio
            alt="Your Name"
          />
          <p>
            Thane's Best Digital Marketing agency that believes in taking your
            ideas to the pinnacle of success.
          </p>
        </div>

        <ul>
          <li>Services</li>
          <li>Social Media Marketing</li>
          <li>Mobile Development</li>
          <li>Branding and Designing</li>
          <li>Website Development</li>
          <li>UI/UX Designing</li>
          <li>Search Engine Optimization </li>
        </ul>
        <ul>
          <li>Quick Links</li>
          <li>Our Work</li>
          <li>About Us</li>
          <li>Services</li>
          <li>
            Careers <span>We're hiring</span>
          </li>
        </ul>
        <ul>
          <li>Reach us</li>
          <li>
            <Image
              src="/./images/footericons/email.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            biz@digillence.in
          </li>
          <li>
            <Image
              src="/./images/footericons/location.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
          <li>
            <Image
              src="/./images/footericons/phone.png" // Route of the image file
              height={144} // Desired size with correct aspect ratio
              width={144} // Desired size with correct aspect ratio
              alt="Your Name"
            />
            +91 86559974455
          </li>
        </ul>
      </footer>
      <div className={styles.bottom}>2022 , Digiligence copyright</div>
    </div>
  );
}
